controller_manager:
  ros__parameters:
    update_rate: 100
    use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    joint_trajectory_controller:
        type: position_controllers/JointGroupPositionController

joint_state_broadcaster:
  ros__parameters:
    publish_rate: 100

joint_trajectory_controller:   
  ros__parameters:
    state_publish_rate: 100.0 # Defaults to 50
    action_monitor_rate: 20.0 # Defaults to 20
    joints:
        - FR1_joint
        - FR2_joint
        - FR3_joint
        - FL1_joint
        - FL2_joint
        - FL3_joint
        - RR1_joint
        - RR2_joint
        - RR3_joint
        - RL1_joint
        - RL2_joint
        - RL3_joint
            